public class Pays {
    public static String[] get() {
        return new String[]{
                "Chine",
                "Inde",
                "États-Unis",
                "Indonésie",
                "Brésil",
                "Pakistan",
                "Nigeria",
                "Bangladesh",
                "Russie",
                "Japon",
                "Mexique",
                "Philippines",
                "Éthiopie",
                "Viêt Nam",
                "Égypte",
                "Turquie",
                "Allemagne",
                "Iran",
                "République démocratique du Congo",
                "France",
                "Thaïlande",
                "Royaume-Uni",
                "Italie",
                "Birmanie",
                "Tanzanie",
                "Corée du Sud",
                "Afrique du Sud",
                "Espagne",
                "Colombie",
                "Kenya",
                "Ukraine",
                "Argentine",
                "Algérie",
                "Pologne",
                "Ouganda",
                "Canada",
                "Soudan",
                "Maroc",
                "Irak",
                "Afghanistan",
                "Arabie saoudite",
                "Venezuela",
                "Pérou",
                "Malaisie",
                "Ouzbékistan",
                "Népal",
                "Ghana",
                "Corée du Nord",
                "Yémen",
                "Mozambique",
                "Australie",
                "Taïwan",
                "Côte d'Ivoire",
                "Syrie",
                "Madagascar",
                "Sri Lanka",
                "Cameroun",
                "Roumanie",
                "Angola",
                "Burkina Faso",
                "Pays-Bas",
                "Kazakhstan",
                "Chili",
                "Mali",
                "Niger",
                "Malawi",
                "Cambodge",
                "Équateur",
                "Guatemala",
                "Zambie",
                "Zimbabwe",
                "Sénégal",
                "Rwanda",
                "Soudan du Sud",
                "Guinée",
                "Tchad",
                "Belgique",
                "Cuba",
                "Tunisie",
                "Bolivie",
                "République tchèque",
                "Somalie",
                "Portugal",
                "République dominicaine",
                "Bénin",
                "Haïti",
                "Hongrie",
                "Grèce",
                "Suède",
                "Biélorussie",
                "Burundi",
                "Azerbaïdjan",
                "Honduras",
                "Autriche",
                "Émirats arabes unis",
                "Suisse",
                "Tadjikistan",
                "Israël",
                "Bulgarie",
                "Togo",
                "Serbie",
                "Laos",
                "Jordanie",
                "Paraguay",
                "Papouasie-Nouvelle-Guinée",
                "Érythrée",
                "Libye",
                "Nicaragua",
                "Salvador",
                "Liban",
                "Sierra Leone",
                "Danemark",
                "Kirghizistan",
                "Finlande",
                "Slovaquie",
                "Singapour",
                "République centrafricaine",
                "Turkménistan",
                "Norvège",
                "Costa Rica",
                "République du Congo",
                "Irlande",
                "Palestine",
                "Géorgie",
                "Croatie",
                "Nouvelle-Zélande",
                "Liberia",
                "Bosnie-Herzégovine",
                "Oman",
                "Panama",
                "Moldavie",
                "Mauritanie",
                "Uruguay",
                "Albanie",
                "Arménie",
                "Mongolie",
                "Lituanie",
                "Koweït",
                "Jamaïque",
                "Qatar",
                "Namibie",
                "Botswana",
                "Macédoine",
                "Slovénie",
                "Lettonie",
                "Lesotho",
                "Gambie",
                "Kosovo",
                "Guinée-Bissau",
                "Gabon",
                "Swaziland",
                "Maurice",
                "Bahreïn",
                "Estonie",
                "Trinité-et-Tobago",
                "Timor oriental",
                "Chypre",
                "Fidji",
                "Djibouti",
                "Comores",
                "Guyana",
                "Bhoutan",
                "Guinée équatoriale",
                "Monténégro",
                "Salomon",
                "Suriname",
                "Luxembourg",
                "Cap-Vert",
                "Malte",
                "Brunei",
                "Maldives",
                "Belize",
                "Islande",
                "Bahamas",
                "Barbade",
                "Vanuatu",
                "Samoa",
                "Sao Tomé-et-Principe",
                "Sainte-Lucie",
                "Grenade",
                "Tonga",
                "Micronésie",
                "Kiribati",
                "Saint-Vincent-et-les Grenadines",
                "Seychelles",
                "Antigua-et-Barbuda",
                "Andorre",
                "Dominique",
                "Îles Marshall",
                "Saint-Christophe-et-Niévès",
                "Liechtenstein",
                "Monaco",
                "Saint-Marin",
                "Palaos",
                "Tuvalu",
                "Nauru",
                "Vatican"
        };
    }
}
